### ISSUE TITLE
[Request] Could you design a theme for Telegram mobile?

### ISSUE THREAD

**Issue by steadyoak** [Roboron3042/Cyberpunk-Neon#11]
Dear dear Roboron,

I love your themes. They are exactly the feeling to the image of neon color pattern of cyberpunk.

I saw you have already make one for the desktop version of telegram. It can not be imported into the mobile version of telegram.

Could you design it for that? Love you. ❤️❤️❤️

**Comment by Roboron3042** [comment]
Why did you close this issue? Did you find something similar?

**Comment by steadyoak** [comment]
I closed it because I found telegram mobile gives us too few customizable options. It can not be done on it. 😂

**Comment by Roboron3042** [comment]
Ah. See, when I started cyberpunk-neon two years ago, Telegram desktop theme is one of the first things I did (see the screenshot i posted on Reddit when I first showed my creation https://i.redd.it/lw08k55mkv921.png). And I remember to start working on the mobile version, too. What I don't remember is the reason I dropped that idea haha, but it may be what you have found ^^

Anyway, I was going to dismiss this, since I'm no longer using Telegram mobile. I'm now using a Pinephone which is capable of running Telegram desktop so I don't have any need for this :^)

**Comment by nitanmarcel** [comment]
@steadyoak You can convert the desktop theme to Android using this telegram bot: https://t.me/Themesporterbot

The result might still need some tweaks but so far looks good.

https://drive.google.com/file/d/1AcdLefBeoecDWQtO4nsvSszvyhBTay9y/view?usp=drivesdk

**Comment by nitanmarcel** [comment]
@steadyoak @Roboron3042 Made a PR with the theme, fixed some things as you can see from the comparation with the photo below. The one I've updated before above had some things fixed but I didn't liked the pinned chat overlay so I removed it. Looks way nicer

https://t.me/addtheme/N7rYB60wL13Y9F7g

![IMG_20201104_113837_676](https://user-images.githubusercontent.com/41646249/98095170-e1f63680-1e92-11eb-8b7c-ba2b5e665753.jpg)
